import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    header: {
        padding: 16,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    languageButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f7ff',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        gap: 4,
    },
    languageButtonText: {
        color: '#0066cc',
        fontSize: 14,
        fontWeight: '500',
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333333',
    },
    searchTypeContainer: {
        flexDirection: 'row',
        padding: 8,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    searchTypeButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 12,
        gap: 8,
        borderRadius: 8,
    },
    searchTypeButtonActive: {
        backgroundColor: '#f0f7ff',
    },
    searchTypeText: {
        fontSize: 16,
        color: '#666666',
    },
    searchTypeTextActive: {
        color: '#0066cc',
        fontWeight: '500',
    },
    searchContainer: {
        flexDirection: 'row',
        padding: 16,
        gap: 8,
    },
    input: {
        flex: 1,
        height: 40,
        borderWidth: 1,
        borderColor: '#cccccc',
        borderRadius: 8,
        paddingHorizontal: 12,
        backgroundColor: '#ffffff',
    },
    searchButton: {
        backgroundColor: '#0066cc',
        paddingHorizontal: 16,
        justifyContent: 'center',
        borderRadius: 8,
    },
    searchButtonText: {
        color: '#ffffff',
        fontWeight: 'bold',
    },
    loader: {
        marginTop: 24,
    },
    routeInfo: {
        backgroundColor: '#ffffff',
        padding: 12,
        marginHorizontal: 16,
        borderRadius: 8,
        marginBottom: 8,
    },
    routeInfoText: {
        fontSize: 16,
        color: '#333333',
    },
    listContainer: {
        padding: 16,
        paddingTop: 8,
    },
    stopItem: {
        backgroundColor: '#ffffff',
        borderRadius: 8,
        padding: 16,
        marginBottom: 8,
        elevation: 2,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    stopHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    stopSequence: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333333',
    },
    destination: {
        fontSize: 14,
        color: '#666666',
    },
    etaContainer: {
        gap: 4,
    },
    etaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    etaTime: {
        fontSize: 14,
        color: '#0066cc',
    },
    etaRemark: {
        fontSize: 12,
        color: '#666666',
    },
    noEta: {
        color: '#999999',
        fontStyle: 'italic',
    },
    nearbyContainer: {
        flex: 1,
    },
    nearbyHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        paddingBottom: 8,
    },
    nearbyTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333333',
    },
    refreshButton: {
        padding: 8,
    },
    nearbyStopItem: {
        backgroundColor: '#ffffff',
        borderRadius: 8,
        padding: 16,
        marginBottom: 8,
        elevation: 2,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    nearbyStopHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    nearbyStopName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333333',
        flex: 1,
    },
    nearbyStopDistance: {
        fontSize: 14,
        color: '#666666',
        backgroundColor: '#f0f0f0',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    routesScroll: {
        flexGrow: 0,
    },
    nearbyRouteItem: {
        backgroundColor: '#f0f7ff',
        borderRadius: 8,
        padding: 12,
        marginRight: 8,
        minWidth: 100,
        alignItems: 'center',
    },
    nearbyRouteNumber: {
        fontSize: 16,
        fontWeight: '600',
        color: '#0066cc',
        marginBottom: 4,
    },
    nearbyRouteEta: {
        fontSize: 14,
        color: '#666666',
    },
    noRoutes: {
        color: '#999999',
        fontStyle: 'italic',
        padding: 8,
    },
    errorText: {
        color: '#ff3b30',
        textAlign: 'center',
        margin: 16,
    },
    stopInfo: {
        flex: 1,
        marginRight: 8,
    },
    stopName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333333',
        marginBottom: 4,
    },
    stopSequence: {
        fontSize: 12,
        color: '#666666',
    },
    stopHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    destination: {
        fontSize: 14,
        color: '#666666',
        textAlign: 'right',
    },
    searchButtonDisabled: {
        backgroundColor: '#cccccc',
    },
    directionToggle: {
        backgroundColor: '#ffffff',
        marginHorizontal: 16,
        marginVertical: 8,
        borderRadius: 12,
        padding: 12,
        elevation: 2,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    directionToggleDisabled: {
        opacity: 0.6,
    },
    directionContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    directionTextContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    directionPrimary: {
        fontSize: 14,
        color: '#333333',
        fontWeight: '500',
    },
    directionArrow: {
        marginHorizontal: 4,
    },
    toggleIconContainer: {
        backgroundColor: '#f0f7ff',
        padding: 8,
        borderRadius: 8,
        marginLeft: 12,
    },
    routeHeader: {
        backgroundColor: '#ffffff',
        marginHorizontal: 16,
        marginVertical: 8,
        borderRadius: 12,
        padding: 16,
        elevation: 2,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    routeHeaderDisabled: {
        opacity: 0.6,
    },
    routeHeaderClickable: {
        backgroundColor: '#f8f9fa',
    },
    routeContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    routeNumber: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#0066cc',
        minWidth: 50,
    },
    routeDirectionContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 12,
        gap: 8,
    },
    routeTerminal: {
        fontSize: 14,
        color: '#333333',
        flex: 1,
        textAlign: 'center',
    },
    directionArrow: {
        marginHorizontal: 4,
    },
    toggleIcon: {
        backgroundColor: '#e8f2ff',
        padding: 8,
        borderRadius: 8,
        marginLeft: 8,
    },
});